mysql:
  image: mysql:5.7.12
  container_name: wisemapping_mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
  volumes:
   - ./wisemapping/mysql:/var/lib/mysql
  restart: always

app:
  build: docker
  container_name: wisemapping_app
  restart: always
  links:
   - mysql:mysql
  ports:
   - 7548:8080
  environment:
   - VIRTUAL_HOST=wisemapping.misterbanal.net

